### ISSUE TITLE
Widget tidak tampil

### ISSUE THREAD

**Issue by syaefulsyamsuri** [teguhsaint/OpenSID-Themes-Cosmo-V2.2#2]
![Screenshot_117](https://user-images.githubusercontent.com/84442363/118782062-e8d91980-b8b7-11eb-9ffc-cc58381af9f6.png)

**Comment by teguhsaint** [comment]
> 
> 
> ![Screenshot_117](https://user-images.githubusercontent.com/84442363/118782062-e8d91980-b8b7-11eb-9ffc-cc58381af9f6.png)

itu settingan widget di siteman udah ada belum pak ?

**Comment by syaefulsyamsuri** [comment]
![Screenshot_118](https://user-images.githubusercontent.com/84442363/118885827-6d608200-b922-11eb-80b9-8f2bd452e1e5.png)

**Comment by syaefulsyamsuri** [comment]
setingannya seperti itu Mas
